import { Annotation, MessagesAnnotation } from "@langchain/langgraph";

export const GptResearcherGraphAnnotation = Annotation.Root({
  /**
   * The chat history to research.
   * Will use the latest user message as the research query.
   */
  ...MessagesAnnotation.spec,
  /**
   * The research query derived from the user's latest message.
   */
  query: Annotation<string>,
  /**
   * The full research report generated by GPT Researcher.
   */
  researchReport: Annotation<string>,
  /**
   * Whether the research completed successfully.
   */
  researchComplete: Annotation<boolean>,
});

export type GptResearcherState = typeof GptResearcherGraphAnnotation.State;
